config/routes.rb
Rails.application.routes.draw do
  get 'experience/index'
  get 'experience/show'
  get 'background/index'
  get 'space/index'
  get 'blogs/index'
  get 'blogs/why2023'
  get 'blogs/blocks_and'
  get 'blogs/tricks'
  get 'blogs/method_arguments'
  get 'blogs/regex'
  get 'home/index'
  get 'text_space/index'
  post 'text_space/create'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
   root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cp_text.rb
class CpText < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/background_controller.rb
class BackgroundController < ApplicationController
  def index
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end

  def why2023
  end

  def blocks_and
  end

  def tricks
  end

  def method_arguments
  end

  def regex
  end
end

app/controllers/experience_controller.rb
class ExperienceController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @client_address = nil

    @reviews = {
        stuart: {
            linkedin: 'https://www.linkedin.com/in/stu-chaney',
            position: 'Stuart Chaney Founder & CEO at Rivo',
            image_src: 'Stuart Chaney.png',
            review_text: ' Hands down one of the best Rails developers I have ever worked with in my 10+ years of software. Amazing in every department',
            stars_a: 5,
            stars_b: 5,
        },
        todd: {
            image_src: 'Todd Kriney.jfif',
            position: 'Todd Kriney Co-Founder at Hit Run Steal',
            linkedin: 'https://www.linkedin.com/in/todd-kriney-13b48827',
            review_text: "The best programmer I have ever worked with. He worked on my site for over a year full time.
                          Was always available to have a call or chat. His work was great.
                          Would highly recommend working with Serghei on any RoR project.",
            stars_a: 5,
            stars_b: 5,
        },
        nico: {
            linkedin: 'https://be.linkedin.com/in/nicovanhoof',
            image_src: 'NicoVanHoof.png',
            position: 'Nico Van Hoof CEO at Globe Digital Data',
            review_text: 'Serghei is a true hard-worker he has excellent professional skills and he is a very good team member. He started as a Senior Developer and ended as a Solid Team Leader.',
            stars_a: 5,
            stars_b: 5,
        },
        david: {
            position: '"David Sinton Co-Founder at Quiet Owl"',
            linkedin: 'https://www.linkedin.com/in/davidsinton',
            image_src: 'david Sinton.jfif',
            review_text: 'Did a great job on a challenging project.
                          Was always available when I needed him, and was always helpful and eager to please.',
            stars_a: 5,
            stars_b: 5,

        }
    }

  end
end

app/controllers/space_controller.rb
class SpaceController < ApplicationController
  def index
  end
end

app/controllers/text_space_controller.rb
class TextSpaceController < ApplicationController
  http_basic_authenticate_with name: ENV["CP_USER"].to_s, password: ENV["CP_PASSWORD"].to_s

  def index
   @texts = CpText.all
  end

  def create
    Rails.logger.info "create!"
    if params[:cptext][:value] == "remove_all"
      CpText.destroy_all
    else
      CpText.create(value: params[:cptext][:value].to_s)
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def my_email
    ENV["MY_GIT_EMAIL"]
  end

  def stars times=1
    tag.i(class:  "fa fa-star rating-color") * times
  end

  def http_protocol
     Rails.env == 'production' ? 'https' : 'http'
  end
end

app/helpers/background_helper.rb
module BackgroundHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/experience_helper.rb
module ExperienceHelper

  def link_image src:,class_name: ''
    image_src = "/images/#{src}"
    link_to(image_src, target: "_blank") do
      image_tag(image_src,class: class_name)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/space_helper.rb
module SpaceHelper
end

app/helpers/text_space_helper.rb
module TextSpaceHelper
end

app/views/background/index.html.erb
<h1>Background#index</h1>
<p>Find me in app/views/background/index.html.erb</p>

app/views/blogs/_side_menu.html.erb
<div class="sidebar">

  <ul id="vertical_sidebar">
    <h2>Articles</h2>
    <%= link_to "Why Rails in 2023", blogs_why2023_path , class: 'nav-link py-2 px-0 px-lg-2' %>

    <%= link_to "About Regex", blogs_regex_path , class: 'nav-link py-2 px-0 px-lg-2' %>

    <%= link_to "About Tricks", blogs_tricks_path , class: 'nav-link py-2 px-0 px-lg-2' %>

    <%= link_to "Method Args", blogs_method_arguments_path , class: 'nav-link py-2 px-0 px-lg-2' %>

    <%= link_to "Blocks", blogs_blocks_and_path , class: 'nav-link py-2 px-0 px-lg-2' %>

  </ul>

  <div id="horizontal_sidebar">

    <h2>Articles</h2>

    <%= link_to "Why Rails in 2023", blogs_why2023_path , class: 'nav-link py-2 px-0 px-lg-2' %>

    <%= link_to "About Regex", blogs_regex_path , class: 'nav-link py-2 px-0 px-lg-2' %>

    <%= link_to "About Tricks", blogs_tricks_path , class: 'nav-link py-2 px-0 px-lg-2' %>

    <%= link_to "Method Args", blogs_method_arguments_path , class: 'nav-link py-2 px-0 px-lg-2' %>

    <%= link_to "Blocks", blogs_blocks_and_path , class: 'nav-link py-2 px-0 px-lg-2' %>

  </div>

</div>

app/views/blogs/_style_blogs.html.erb
<style>
  h1 {
    margin-bottom: 30px;
    align-content: center;
    margin-left: auto;
    margin-right: auto;
  }

  h2{font-size: 1.8em;}

  header{
    margin-bottom: 50px;
  }


  ol {
    list-style: decimal;
    margin: 0;
    padding: 0;
  }

  li {
    margin: 10px 0;
  }

  strong {
    font-weight: bold;
  }

  main.blog {
    font-family: 'Montserrat', sans-serif;
    margin: 50px;
    margin-top: 100px;
  }

  @media only screen and (min-width: 1200px) {
  .sidebar {
    position: fixed;
    top: 0;
    left: 0;
    width: 200px;
    height: 100%;
    background-color: #f2f2f2;
    padding: 20px;
    box-sizing: border-box;
    padding-top: 100px;
  }

    #vertical_sidebar{
      display: block;
    }

    #horizontal_sidebar{
      display: none;
    }

    .content {
      margin-left: 200px;
      padding: 20px;
      box-sizing: border-box;
    }
  }

  @media only screen and (max-width: 1200px) {
    .content {
      margin-left: 10px;
      padding: 20px;
      box-sizing: border-box;
    }

    .sidebar {
      position: fixed;
      top: 0;
      left: 30px;

      width: 90%;
      height: 10%;
      min-height: 200px;
      background-color: #f2f2f2;
      padding: 20px;
      box-sizing: border-box;
      padding-top: 100px;
      z-index: 999;
      margin-bottom: 180px;
    }

    #horizontal_sidebar{
      display: inline-block;
      width: 100%;
      min-height: 100px;
    }

    #horizontal_sidebar a{
      display: inline;
    }

    #horizontal_sidebar h2{
      display: block;
      margin-left: 35%;
    }

    #vertical_sidebar{
      display: none;
    }
    .content{
      margin-top: 300px;
    }
  }


  .sidebar ul {
    list-style: none;
    padding: 0;
    margin: 20px 0;
  }

  .sidebar li {
    margin: 10px 0;
  }

  .sidebar a {
    text-decoration: none;
    color: #000;
    font-weight: bold;
  }



  h1 {
    margin-top: 0;
  }
    body{
      background-image: url("/images/james-harrison-laptop_image.jpg");
      background-repeat: no-repeat, repeat;
      background-position: center; /* Center the image */
      background-size: cover;
      background-attachment: fixed;
      background-color: black;
    }

  .content{
    background-color: #595959;
    color: white;
    opacity: 0.90;
  }

    .hljs-copy-button{
      color: #fff;
      background-color: #28a745;
      border-color: #28a745;

    }
</style>

app/views/blogs/blocks_and.html.erb
<%= render 'style_blogs' %>

<%= render 'side_menu' %>

<main class="blog">
  <div class="content">
    <h2>Blocks in Ruby</h2>
    <p>
      In this article, we'll explore the concepts of blocks, procs, and lambdas in Ruby and show you how to use them to write more elegant and efficient code.
    </p>

    <p>
      A block is a piece of code that can be passed to a method as an argument.
      It's a way to group together a set of statements that can be executed together.
      Blocks are defined using braces {} or the do...end keywords. Here's an example of a block that prints the elements of an array:
    </p>

    <pre>
      <code class="language-ruby">
          array = [1, 2, 3, 4, 5]
          array.each { |element| puts element }
      </code>
    </pre>

    <p>In this example, the each method is passed a block that prints out each element of the array.</p>
    <h2> Procs in Ruby </h2>
    <p>
      A proc is an object that encapsulates a block of code.
      It can be stored in a variable, passed as an argument to a method, or returned from a method.
      Here's an example of a proc that doubles a number:
    </p>

    <pre>
      <code class="language-ruby">
        doubler = Proc.new { |n| n * 2 }
        result = doubler.call(5)
        puts result # Output: 10
      </code>
    </pre>
    <p>
      In this example, we create a proc using the Proc.new method and pass it to the call method to double the number 5.
    </p>

    <h2>Lambdas in Ruby</h2>
    <p>
      A lambda is a type of proc that enforces strict argument checking. Unlike a regular proc,
      a lambda will raise an error if the wrong number of arguments is passed to it.
      Here's an example of a lambda that doubles a number:
    </p>

    <pre>
        <code class="language-ruby">
          doubler = lambda { |n| n * 2 }
          result = doubler.call(5)
          puts result # Output: 10
      </code>
    </pre>

    <p>
      In this example, we create a lambda using the lambda keyword and pass it to the call method to double the number 5.
    </p>

    <h2>Differences Between Procs and Lambdas</h2>

    <p>
      The main difference between procs and lambdas is how they handle argument checking.
      A proc will simply ignore any extra arguments that are passed to it, while a lambda will raise an error.
      Here's an example that demonstrates this difference:
    </p>

    <pre>
      <code class="language-ruby">
        # Proc example
        proc = Proc.new { |a, b| puts "#{a} #{b}" }
        proc.call(1, 2, 3) # Output: "1 2"

        # Lambda example
        lambda = lambda { |a, b| puts "#{a} #{b}" }
        lambda.call(1, 2, 3) # Output: ArgumentError (wrong number of arguments (given 3, expected 2))
      </code>
    </pre>

    <p>
      In this example, the proc ignores the extra argument and prints out "1 2", while the lambda raises an error.
    </p>

    <h2>
      Conclusion
    </h2>

    <p>
      In this article, we've explored the concepts of blocks, procs, and lambdas in Ruby.
      Blocks are a way to group together a set of statements that can be executed together,
      procs are objects that encapsulate a block of code,
      and lambdas are a type of proc that enforces strict argument checking.
      By understanding these concepts, you can write more elegant and efficient code in Ruby.
    </p>
  </div>
</main>

app/views/blogs/index.html.erb
<%= render 'style_blogs' %>
<%= render 'side_menu' %>

<main class="blog">
  <div class="content">
    <h2>
      Here you will find some Articles about Ruby on Rails.
    </h2>

    <p>
      Please feel free to copy past this code and use it without any restrictions!
    </p>
  </div>
</main>

app/views/blogs/method_arguments.html.erb
<%= render 'style_blogs' %>
<%= render 'side_menu' %>

<main class="blog">
  <div class="content">
    <p>In Ruby, function arguments give a good flexibility on how they can be used and
      in this short article I will show you how you can use them.
    </p>

    <h2>Defining and usage of Function Arguments</h2>

    <p>
      To define function arguments in Ruby, you simply list them inside the parentheses(or without) after the method name. Here's an example of a method that takes two arguments:
    </p>

    <pre>
      <code class="language-ruby">
    def greeting(name, age)
      puts "Hello, #{name}! You are #{age} years old."
    end

    #Parentheses are not obligatory:

    def greeting name, age
      puts "Hello, #{name}! You are #{age} years old."
    end
      </code>
    </pre>

    <h2>
      Default Values for Function Arguments
    </h2>
    <p>
      In Ruby, you can specify default values for function arguments. If an argument is not passed to the method, the default value will be used instead.
      Here's an example of a method that takes an optional argument with a default value:
    </p>

    <pre>
      <code class="language-ruby">
    def greeting(name, age = 30)
      puts "Hello, #{name}! You are #{age} years old."
    end

    greeting("Alice") # Output: "Hello, Alice! You are 30 years old."
    greeting("Bob", 25) # Output: "Hello, Bob! You are 25 years old."
      </code>
     </pre>


    <h2>Using Named Arguments in Ruby </h2>
    <p>
      In Ruby 2.0 and later versions, you can use named arguments to make your code more readable and maintainable.
      Named arguments allow you to specify arguments by name instead of position.
      Here's an example:
    </p>


    <pre>
    <code class="language-ruby">
    def greeting(name:, age: 30)
      puts "Hello, #{name}! You are #{age} years old."
    end

    greeting(name: "Alice") # Output: "Hello, Alice! You are 30 years old."
    greeting(name: "Bob", age: 25) # Output: "Hello, Bob! You are 25 years old."
    </code>
  </pre>


    <h2>Using method reference as an function argument</h2>
    <p>
      Ruby enables using a method reference as method argument that can be used later(by using .call)
    </p>

    <pre>
    <code class="language-ruby">
    def execute_method method,text
      method.call text
    end

    def display_text(txt)
      puts txt
    end

    method_obj  = self.method("display_text")
    execute_method(method_obj,"Hello from the start method!")
    </code>
  </pre>

    <p>
      In this example, we define a method called 'execute_method' that takes two named arguments: method and text.
      And 'Method' argument will be the one to point to display_text method so it can be called dynamically.
    </p>

    <h2>Using Block as an method argument</h2>

    <p>
      Ruby enables using blocks as method arguments similar to method references(from above) but with a different syntax.
    </p>

    <pre>
    <code class="language-ruby">
    def use_block a = "Hey"
      yield a
      yield a
    end

    use_block{|s| puts 'where is the money? #{s} '}
    </code>
    </pre>

    <p>
      In this example, define block while we call 'use_block' method. And we call it twice by using special keyword 'yield'.
    </p>

    <h2>Use Variable Arguments to Capture as Many Values as Necessary</h2>

    <p>
      Ruby enables using dynamic amount of arguments for all it's methods.
    </p>


    <pre>
    <code class="language-ruby">
    def print_all(*args)
    #...
    end

    print_all(1, 2, 3, 'sdf', 5,5)
    </code>
    </pre>

    <h2>Use Hash Arguments to Capture as Many Values as Necessary</h2>

    <p>
      Ruby enables using hash as a dynamic list of arguments
    </p>
    <pre>
    <code class="language-ruby">
    def foo(regular, hash={})
      puts "regular: #{regular}"
      puts "hash: #{hash}"
      puts "a: #{hash[:a]}"
      puts "b: #{hash[:b]}"
    end

    foo("regular argument", a: 12, :b => 13)

     </code>
    </pre>


    <h2> Double splat operator(**) for arguments </h2>

    <p>
      The double splat operator came out back in Ruby 2.0.
      It’s pretty similar to the original splat with one difference:
      it can be used for hashes! So you can random amount of key value arguments and ruby will read it as an argument
    </p>
    <pre>
    <code class="language-ruby">
        def foo(a, *b, **c)
            [a, b, c]
        end

      foo(10, 20, 30, d: 40, e: 50) will result to: [10, [20, 30], {:d=>40, :e=>50}]
       </code>
    </pre>

    <p>
      In this example we define a method 'foo' it will get all 3 types of arguments: simple, splash for arrays and double splash for hashes.
    </p>

  </div>
</main>

app/views/blogs/why2023.html.erb
<%= render 'style_blogs' %>
<%= render 'side_menu' %>

<main class="blog">

  <div class="content">
    <h1> Why Ruby on Rails in 2023</h1>
    <p>
      Ruby on Rails is a popular open-source web framework that has been
      around since 2004. While some may argue that it has lost its shine and
      popularity over the years, Ruby on Rails is still a good choice for web
      development in 2023. Here are my arguments below:
    </p>
    <ol>
      <li>
        <strong>Rapid Development</strong>: Ruby on Rails is known for its
        ability to quickly develop web applications. Its "convention over
        configuration" philosophy enables developers to build web applications
        faster by using pre-built components, libraries, and tools.
      </li>
      <li>
        <strong>Mature Ecosystem</strong>: Ruby on Rails has a mature ecosystem
        with a vast collection of libraries and plugins that make web development
        more accessible and efficient. The community-driven development of Ruby on
        Rails has led to the creation of a large number of gems (libraries) that can
        be easily integrated into the application.
      </li>
      <li>
        <strong>Scalability</strong>: Scalability is a critical factor in modern web
        development, and Ruby on Rails is designed to be scalable. The framework is
        built on the Model-View-Controller (MVC) architecture, which separates the
        concerns of the application and makes it easier to scale. Additionally,
        Ruby on Rails applications can be easily deployed on cloud platforms like
        Heroku and AWS, which provides the ability to scale the application as needed.
      </li>
      <li>
        <strong>Stability and Security</strong>: Ruby on Rails has been around for
        over a decade, and it has become more stable and secure over time. The Rails
        community is dedicated to ensuring the security and reliability of the
        framework, and regular updates are released to address security
        vulnerabilities and bugs.
      </li>
      <li>
        <strong>Cost-Effective</strong>: Ruby on Rails is an open-source framework,
        and there are no licensing fees or subscription costs associated with it.
        This makes it an ideal choice for startups and small businesses that have
        limited budgets.
      </li>
      <li>
        <strong>Community Support</strong>: The Ruby on Rails community is one of
        the most vibrant and active developer communities. There are many online
        resources, forums, and communities dedicated to supporting Ruby on Rails
        developers. This means that developers can get help with their projects and
        quickly find solutions to problems that they encounter.
      </li>
      <li>
        <strong>At the End:</strong>: Look at this: <a href="https://github.com/rails/rails/commits/main"> Rails GitHub</a> <strong> YES</strong> work in progress :)
        Great day to you my friend!
      </li>

    </ol>
  </div>
</main>

app/views/experience/show.html.erb
<h1>Experience#show</h1>
<p>Find me in app/views/experience/show.html.erb</p>

app/views/home/_reviews.html.erb
<div id="reviews_block"  style="display: none;">

  <div>
    <!--  Render All the reviews -->
    <% @reviews.each do |k,v| %>
      <%= render "review_item",:person => v %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Jura:wght@300" rel="stylesheet">

<div class="home main-content" >

  <video autoplay loop muted playsinline style="position:fixed; top:0px; left:0px; bottom:50px; right:0px; width:100%; height:100%; object-fit:fill">
    <source src="/dron2.mp4" type="video/mp4">
  </video>
  <!--  Drone shot flying along Taksin Bridge over the Chao Phraya River in Bangkok, Thailand.-->
  <!--  Credits to Videvo.-->
  <!--  https://www.videvo.net/video/flying-along-taksin-bridge/456055/-->


  <div id="info-block" style="position: relative">
    <div id="info-content">
      <!--initially blank space and filled step by step-->
    </div>

    <div>
      <%= render 'reviews' %>

      <div id="info-block-hidden" style="visibility: hidden">
        <h2 class="padding-15">
          Hello! My name is <strong> Serghei </strong> and I am <strong> FULL STACK </strong>  Ruby on Rails Developer(since 2010) and Team Leader with over <strong> 13 years</strong> of experience
          and I am ready to bring latest tech to <strong>Boost</strong> your <strong>Business</strong>
        </h2>
        <p>
          If you are trying to create a <strong>GREAT</strong> website or software, or if you experience <strong>ANY</strong> problem with the existing one.
          I will be happy to assist you, because my job is to <strong>HELP</strong> people and I have the necessary <strong>SKILLS</strong> to do so.
          I am not a <strong>Ninja Developer</strong>. I am rather a <strong>Samurai Developer</strong> because my goals are: strong productivity, exceptional quality, happy and protected customer.
        </p>

        <p>
          <strong> Languages:</strong>
         Ruby, JavaScript, SQL, HTML5, CSS3, C#, TypeScript, ERB
        </p>

        <p>
          <strong>Data:</strong> Postgresql,Redis,AWS S3,Oracle,SqlServer,Elasticsearch
        </p>

        <p>
          <strong>Server Management:</strong> AWS EC2, Digital Ocean Droplets, NGinx, Unicorn, Puma
        </p>

        <p>
          <strong>Version Control System:</strong> Git, GitHub, Bitbucket
        </p>

        <p>
          <strong> Frameworks,APIs,Libs:</strong> Shopify,JQuery,Vue.Js,AngularJS 1,AngularJS 2, Ruby on Rails, Sidekiq PRO,Payment Processing(Stripe, Paypal),
          APIs integration(Facebook,Google,Amazon), Fabric.js, Bootstrap
        </p>

        <p>
          <strong> Concepts:</strong> OOP,OOD,Agile Software Development,Adaptive Web Design,SEO Optimization
        </p>

        <%= link_to "Get More Details", experience_index_path,class: "btn btn-important" %>  <a class="btn" href = "mailto: <%= my_email %>">Send Me an Email</a>

        <p style="margin-top: 20px;">
          * This Website is Hosted on <strong> AWS EC2 </strong> + <strong> Ruby on Rails : 7.0.4.2 </strong>
        </p>
      </div>
    </div>
  </div>
</div>




<script type="text/javascript">
    var   keyPresses = 1;
    var TYPING_SPEED = 1;
    function homePrintText(currentTextLength){
        localStorage.setItem('myCat', 'Tom');
        var ourHtml = $('#info-block-hidden').html().toString();
        var textBody = ""
        textBody = ourHtml.substring(0,currentTextLength);
        if (currentTextLength >= ourHtml.length){
            clearInterval(typeInterval)
            $('#reviews_block').fadeIn('slow');
            $('#info-block-hidden').html("");
        }
        textBody += "&#9646";
        $("#info-content").html(textBody)
    }

    if (localStorage.getItem('myCat') === 'Tom'){
        var ourHtml = $('#info-block-hidden').html().toString();
        $("#info-content").html(ourHtml)
        $('#reviews_block').fadeIn('slow');
    }
    else {
        var typeInterval = setInterval(() => {
            homePrintText(keyPresses)
            keyPresses += 1
        }, TYPING_SPEED)
    }

</script>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand"  style="font-size: 30px;" href="#">  <%= @client_address.try(:first).try(:address) %> </a>

    <ul class="navbar-nav flex-row flex-wrap bd-navbar-nav">
      <li class="nav-item col-6 col-lg-auto">
        <%= link_to "Home", home_index_path , class: 'nav-link py-2 px-0 px-lg-2' %>
      </li>
    </ul>

    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">

      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel"></h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>

      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <%= link_to "Home", home_index_path , class: 'nav-link py-2 px-0 px-lg-2' %>
          </li>
          <li>
            <%= link_to "Blogs", blogs_index_path , class: 'nav-link py-2 px-0 px-lg-2' %>
          </li>

          <li>
            <%= link_to "Projects", experience_index_path , class: 'nav-link py-2 px-0 px-lg-2' %>
          </li>


          <li>
            <%= link_to "Space.js", space_index_path , class: 'nav-link py-2 px-0 px-lg-2' %>
          </li>

          <li>
            <a href = "mailto: <%= my_email %>">Send Me an Email</a>
          </li>
        </ul>
      </div>
      <span> Copyright © <%= my_email %> </span>
    </div>
  </div>
</nav>

app/views/text_space/index.html.erb
<style>
  h1{margin-top:  80px;margin-left: 40px;}
  table, th, td {
    border: 1px solid;
    padding: 15px;
    margin: 25px 25px 25px 25px;
  }

  .tdscroll {
    max-height: 100px;
    overflow:scroll;
  }

</style>

<script type="">

    let values = <%= raw @texts.to_json %>;
    function copy(id){
        const matchIndex = (element) => element["id"].toString() === id.toString();
        let index = values.findIndex(matchIndex)
        let text = values[index].value;

        if (text && text !=null && text !== ""){
            copyToClipboard(text)
        }
    }

    // Copies a string to the clipboard. Must be called from within an
    // event handler such as click. May return false if it failed, but
    // this is not always possible. Browser support for Chrome 43+,
    // Firefox 42+, Safari 10+, Edge and Internet Explorer 10+.
    // Internet Explorer: The clipboard feature may be disabled by
    // an administrator. By default a prompt is shown the first
    // time the clipboard is used (per session).
    function copyToClipboard(text) {
        if (window.clipboardData && window.clipboardData.setData) {
            // Internet Explorer-specific code path to prevent textarea being shown while dialog is visible.
            return window.clipboardData.setData("Text", text);

        }
        else if (document.queryCommandSupported && document.queryCommandSupported("copy")) {
            var textarea = document.createElement("textarea");
            textarea.textContent = text;
            textarea.style.position = "fixed";  // Prevent scrolling to bottom of page in Microsoft Edge.
            document.body.appendChild(textarea);
            textarea.select();
            try {
                return document.execCommand("copy");  // Security exception may be thrown by some browsers.
            }
            catch (ex) {
                console.warn("Copy to clipboard failed.", ex);
                return prompt("Copy to clipboard: Ctrl+C, Enter", text);
            }
            finally {
                document.body.removeChild(textarea);
            }
        }
    }
</script>

<h1>That's space for text</h1>
<p> </p>

<div style="max-height: 300px; overflow: scroll">
<table class="cbtable">
  <tr>
    <th>Value </th>
    <th>Copy </th>
  </tr>
  <% @texts.each_with_index do |t,i| %>
    <tr>
      <td style="min-width: 300px"><%= t.value %></td>
      <td class="tdscroll"><button onclick="copy(<%= t.id.to_s %>)"> Copy
      </button></td><td>
    </tr>
  <% end %>
</table>
</div>

<%= form_for :cptext,url: text_space_create_url(:protocol => http_protocol) do |f| %>
  Content: <%= f.text_area :value,cols: "50", rows: "5"  %><br />
  <%= f.submit %>
<% end %>